### ISSUE TITLE
other pixi.d.ts

### ISSUE THREAD

**Issue by whizzkid** [natelong/pixi-ts-def#13]
https://github.com/clark-stevenson/PIXI.d.ts

this guys file seems to be up to date. although  completion differs in places between your and his version :)

**Comment by clark-stevenson** [comment]
Wow I am late! 

Guys to cut a long story short. I used Nate's base, got rid of the classes, and re-wrote them to bring order to the definition (it is regularly reviewed against the pixi dev branch).  The last review was Dec 30th so it is very much 98% good to go. 

Then (because pixi repo does not want the d.ts file) then the next best official community place is the phaser.io framework.  

To make us pixi only guys happy, the pixi.d.ts has no dependency, and so, although it is found in the phaser project, it is fine to use by itself with the latest version of pixi.  

Phaser needs it because it uses the latest versions of pixi as a renderer.  So you can assume (and see) that it is being updated now by a larger community and at worst, we are a week away from the dev branch. 

I have closed my repo and pointed to that project. So for the forseeable future, if you need to download pixi and need a definition, you want this one. 

https://github.com/photonstorm/phaser/tree/dev/typescript

Thanks for your original inspiration Nate. When I first came here I had no idea what I was doing and your structure allowed me to not get hung up on the module/export stuff! 

Clark.

**Comment by natelong** [comment]
Well Clark, thanks for all of your help. Without your effort, this would probably still just be a half-working file that doesn't much help the people who might need it. I've removed the source file and updated the readme to point to the Phaser.io version.

Thanks again!
Nate
